# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 'e1ad82c626cc0145c1325f653abb9b32de062dd64ddbfebab5c948bb47b53f8cdd18ef907479b33e41349db4800e44cd2aefcc55bccd908ac143631ceae6b525'
  pubnub_subscribe_key:  'sub-c-de419fd6-1afc-11e7-bc52-02ee2ddab7fe'
  pubnub_publish_key: 'pub-c-69a307eb-52e7-4d66-80e8-b8f3c95da077'
  pubnub_secret_key: 'sec-c-YjNkZjdlMjYtYjFiZC00NWZiLWIyMjctYWM5M2NjMTMyNmQy'
  pubnub_auth_key: 'e1ad82c626cc0145c1325f653abb9b32de062dd64ddbfebab5c948bb47b53f8cdd18ef907479b33e41349db4800e44cd2aefcc55bccd908ac143631ceae6b525'

test:
  secret_key_base: 'e1ad82c626cc0145c1325f653abb9b32de062dd64ddbfebab5c948bb47b53f8cdd18ef907479b33e41349db4800e44cd2aefcc55bccd908ac143631ceae6b525'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
